# apiVersion: v1
# kind: Service
# metadata:
#   name: api
# spec:
#   ports:
#   - port: 5000
#     targetPort: api-port
#     protocol: TCP
#   selector:
#     app: api
  
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api
# spec:
#   selector:
#     matchLabels:
#       app: api
#   strategy:
#     type: Recreate
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: api
#     spec:
#       containers:
#       - image: mkcloudpro/emartapi
#         name: api
#         ports:
#         - containerPort: 5000
#           name: api-port