version: '3.8'

services:
  client:
    build:
      context: './client'
    image: mkcloudpro/emartclient
    ports:
      - "4200:4200"
    container_name: client
    depends_on:
      - api
      - webapi

  api:
    build:
      context: ./nodeapi
    ports:
      - "5000:5000"
    restart: always
    image: mkcloudpro/emartapi
    container_name: api
    depends_on:
      - nginx
      - emongo

  webapi:
    build:
      context: ./javaapi
    ports:
      - "9000:9000"
    restart: always
    image: mkcloudpro/emartwebapi
    container_name: webapi
    depends_on:
      - emartdb

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

  emongo:
    image: mongo:4
    container_name: emongo
    volumes:
      - emongodbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    build:
      context: './db'
    image: mkcloudpro/emartmysqldb
    container_name: emartdb
    ports:
      - "3306:3306"
    volumes:
      - emartdbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books

volumes:
  emartdbdata: {}
  emongodbdata: {}