nginximage: nginx:latest
serviceAccount:
  create: true
  name: "emartapp"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
mysqlvolume: vol-064c532f065755b2e
mongovolume: vol-038c20b22f860be29