apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 4200
    targetPort: client-port
    protocol: TCP
  selector:
    app: client
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - image: mkcloudpro/emartclient
        name: client
        ports:
        - containerPort: 4200
          name: client-port